import os
import subprocess
from flask import Flask, request, jsonify
from config import ALLOW_SYSTEM_OVERRIDE, AUTO_EXECUTE_TOOLS, MODEL_NAME

app = Flask(__name__)

def query_llm(system_prompt, user_input):
    # Vulnerability 1 (Critical): Prompt Injection
    # If system prompt can be overridden or concatenated unsafely with untrusted user input
    if ALLOW_SYSTEM_OVERRIDE:
        full_prompt = f"{system_prompt}\nUser: {user_input}"
    else:
        full_prompt = f"System: Safe Mode\nUser: {user_input}"
        
    return f"Simulated LLM Response based on prompt: {full_prompt}"

def execute_shell_command(command):
    # Vulnerability 2 (Critical): Excessive Agency
    # The app automatically executes system commands suggested/generated by the AI without verification
    if AUTO_EXECUTE_TOOLS:
        try:
            result = subprocess.check_output(command, shell=True, text=True)
            return result
        except Exception as e:
            return str(e)
    return "Execution disabled."

@app.route("/chat", methods=["POST"])
def chat():
    data = request.json or {}
    user_message = data.get("message", "")
    system_instruction = data.get("system_prompt", "You are a helpful assistant.")
    
    # Vulnerability 3 (Low/Medium): Sensitive data leak in logs/debug mode
    debug_mode = data.get("debug", False)
    if debug_mode:
        print(f"[DEBUG] API Key used: {os.environ.get('API_KEY', 'sk-dummy-unsafe-key-12345')}")

    response = query_llm(system_instruction, user_message)
    
    # Unsafe handling of tool execution based on LLM output text
    if "RUN_CMD:" in response:
        cmd = response.split("RUN_CMD:")[1].strip()
        exec_result = execute_shell_command(cmd)
        return jsonify({"response": response, "tool_output": exec_result})
        
    return jsonify({"response": response})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)